--[[
            _     _   _                                             
 _ __  __ _| |___| |_| |_ ___ ___ _ __  __ _ _ _  __ _ __ _ ___ _ _ 
| '_ \/ _` | / -_)  _|  _/ -_)___| '  \/ _` | ' \/ _` / _` / -_) '_|
| .__/\__,_|_\___|\__|\__\___|   |_|_|_\__,_|_||_\__,_\__, \___|_|  
|_|                                                   |___/        

palette-manager.nvim — Neovim colorscheme plugin

Reads base16 colors from an external Lua file (default: ~/.config/palette-manager/theme.lua)
and applies them through a comprehensive highlight table (162 treesitter captures,
67 LSP semantic captures, 30 plugin integrations).

The theme file can be generated by any external tool — the plugin just reads a Lua
table from a configurable path. Set `theme_file` in setup() to customize.

Live-reload: an fs_event watcher watches the theme file and re-applies the colorscheme
within ~1s of changes, so palette switches take effect without restarting Neovim.
]]

local M = {}

---Default path for the theme.lua file
---@return string
local function default_theme_path()
	local xdg = os.getenv('XDG_CONFIG_HOME') or vim.fn.expand('~/.config')
	return xdg .. '/palette-manager/theme.lua'
end

local default_config = {
	theme_file = nil, -- set in setup()
	transparent = false,
	dim_inactive = false,
	term_colors = true,
	ending_tildes = false,
	cmp_itemkind_reverse = false,
	code_style = {
		comments = {},
		conditionals = {},
		keywords = {},
		functions = {},
		namespaces = {},
		parameters = {},
		strings = {},
		variables = {},
	},
	lualine = {
		transparent = false,
	},
	colors = {},
	highlights = {},
	diagnostics = {
		darker = false,
		undercurl = true,
		background = true,
	},
}

---Change palette-manager option
---@param opt string
---@param value any
function M.set_options(opt, value)
	local cfg = vim.g.palette_manager_config
	cfg[opt] = value
	vim.g.palette_manager_config = cfg
end

---Apply the colorscheme (same as ':colorscheme palette-manager')
function M.colorscheme()
	vim.cmd.hi('clear')
	if vim.fn.exists('syntax_on') then
		vim.cmd.syntax('reset')
	end
	vim.o.termguicolors = true
	vim.g.colors_name = 'palette-manager'
	require('palette-manager.highlights').setup()
	require('palette-manager.terminal').setup()
end

---Setup palette-manager options and apply colorscheme
---@param opts table?
function M.setup(opts)
	opts = opts or {}

	-- Set default theme_file if not provided
	if not opts.theme_file then
		opts.theme_file = default_theme_path()
	end

	-- Initialize config
	if not vim.g.palette_manager_config or not vim.g.palette_manager_config.loaded then
		vim.g.palette_manager_config = vim.tbl_deep_extend('keep', {}, default_config)
		M.set_options('loaded', true)
	end

	-- Merge user opts
	vim.g.palette_manager_config =
		vim.tbl_deep_extend('force', vim.g.palette_manager_config, opts)

	-- code_style needs replace, not deep extend
	if opts.code_style then
		local cfg = vim.g.palette_manager_config
		cfg.code_style = vim.tbl_extend('force', cfg.code_style, opts.code_style)
		vim.g.palette_manager_config = cfg
	end

	-- Start the fs_event watcher for live reload
	M._start_watcher()

	-- Apply colorscheme
	M.load()
end

---Load the colorscheme
function M.load()
	vim.cmd.colorscheme('palette-manager')
end

---Start watching the theme file for changes (live reload)
function M._start_watcher()
	local theme_file = vim.g.palette_manager_config.theme_file
	if not theme_file then
		return
	end

	-- Track mtime for FocusGained fallback
	_G._palette_manager_mtime = vim.fn.getftime(theme_file)

	local function reload()
		-- Invalidate cached modules so theme changes are picked up
		for k in pairs(package.loaded) do
			if k:match('^palette%-manager') then
				package.loaded[k] = nil
			end
		end
		require('palette-manager').colorscheme()
		vim.notify('palette-manager: theme reloaded', vim.log.levels.INFO)
	end

	-- fs_event watcher — fires within ~1s of theme file changing on disk
	local fs_event = vim.uv.new_fs_event()
	if fs_event then
		fs_event:start(theme_file, {}, function(err, fname, status)
			if err then
				return
			end
			vim.schedule(function()
				local mtime = vim.fn.getftime(theme_file)
				if mtime > (_G._palette_manager_mtime or 0) then
					_G._palette_manager_mtime = mtime
					reload()
				end
			end)
		end)
	end

	-- FocusGained fallback — catches changes that happened while Neovim was unfocused
	vim.api.nvim_create_autocmd('FocusGained', {
		desc = 'Reload palette-manager theme if file changed',
		group = vim.api.nvim_create_augroup('palette-manager-reload', { clear = true }),
		callback = function()
			local mtime = vim.fn.getftime(theme_file)
			if mtime > (_G._palette_manager_mtime or 0) then
				_G._palette_manager_mtime = mtime
				reload()
			end
		end,
	})
end

return M
